/*
 * Copyright 2023-2026 Omico
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
@file:JvmName("DslGenerator")

package me.omico.elucidator

import me.omico.delusion.kotlin.compiler.analysis.resolveTypeFqName
import me.omico.delusion.kotlin.compiler.delusionKotlinEnvironment
import me.omico.elucidator.function.addDslScopeExtensionFunctions
import me.omico.elucidator.function.custom.addTypeExtensionFunctions
import me.omico.elucidator.psi.addDslExtensionsFromPsi
import me.omico.elucidator.psi.extension.addAnnotateExtensionFunctions
import me.omico.elucidator.psi.utility.findChildren
import me.omico.elucidator.type.addDslBuilderClass
import me.omico.elucidator.type.addDslScopeInterface
import me.omico.elucidator.utility.clearDirectory
import org.jetbrains.kotlin.psi.KtClass
import org.jetbrains.kotlin.psi.KtFile
import kotlin.io.path.Path
import kotlin.system.exitProcess

fun main(arguments: Array<String>) {
    val kotlinpoetSourceDirectory = Path(arguments[0])
    val outputDirectory = Path(arguments[1])
    outputDirectory.clearDirectory()
    delusionKotlinEnvironment(listOf(kotlinpoetSourceDirectory)) {
        val kotlinFiles = sourceFiles.filterIsInstance<KtFile>()
        val annotatableSpecFqNames = kotlinFiles.filterSpecFqNames("com.squareup.kotlinpoet.Annotatable")
        generatedTypes.forEach { type ->
            ktFile(GENERATED_PACKAGE_NAME, type.generatedFileName) {
                addFileComment(GENERATED_HEADER_COMMENT)
                addDslScopeInterface(type)
                addDslBuilderClass(type)
                addDslScopeExtensionFunctions(type)
                addDslExtensionsFromPsi(kotlinFiles)
                addTypeExtensionFunctions(type)
                addAnnotateExtensionFunctions(annotatableSpecFqNames, type)
                writeTo(outputDirectory)
            }
        }
    }

    // TODO https://youtrack.jetbrains.com/issue/KT-73127
    exitProcess(0)
}

private fun List<KtFile>.filterSpecFqNames(superTypeFullQualifierName: String): Set<String> =
    asSequence()
        .flatMap { ktFile -> ktFile.findChildren<KtClass>() }
        .filter { ktClass ->
            ktClass
                .getSuperTypeList()
                ?.entries
                ?.any { it.typeReference?.resolveTypeFqName()?.asString() == superTypeFullQualifierName } == true &&
                ktClass.name?.endsWith("Spec") == true
        }.mapNotNull { it.fqName?.asString() }
        .toSortedSet()

internal const val GENERATED_PACKAGE_NAME = "me.omico.elucidator"

private val GENERATED_HEADER_COMMENT: String =
    """
    |
    |Generated by DslGenerator from Elucidator. Do not edit directly!!!
    |
    """.trimMargin()
